version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  module_system = "es-modules"
  dialect = "typescript"
  style_guide="airbnb"
  

[[transformers]]
name = "prettier"
enabled = true