
[context.production]
  environment = { NEXT_PUBLIC_AUTH_URL = "https://auth--message.anothercat.me" }
    

[context.branch-deploy]
  environment = { NEXT_PUBLIC_AUTH_URL = "https://auth--staging--message.anothercat.me" }
    

